version: '3.8'

services:
  auth-service:
    build: ./microservices/auth-service
    container_name: auth-service
    ports:
      - "3001:3001"
    env_file:
      - ./microservices/auth-service/.env  # Load environment variables from .env file
    volumes:
      - .:/usr/src/app  # Bind mount the current directory to the container
    networks:
      - auth-network
    depends_on:
      - mongodb
    restart: unless-stopped

  order-service:
    build: ./microservices/order-service
    container_name: order-service
    ports:
      - "3002:3002"
    env_file:
      - ./microservices/order-service/.env  # Load environment variables from .env file
    volumes:
      - .:/usr/src/app  # Bind mount the current directory to the container
    networks:
      - auth-network
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"  # Expose MongoDB port
    networks:
      - auth-network
    volumes:
      - mongodb_data:/data/db  # Persist MongoDB data

networks:
  auth-network:
    driver: bridge

volumes:
  mongodb_data:
